site_name: CrOSSD Documentation
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
use_directory_urls: false
extra:
  generator: false
  # social:
  #   - icon: fontawesome/solid/laptop-medical
  #     link: https://health.crossd.tech
  #     name: health.crossd.tech
  #   - icon: fontawesome/solid/blog
  #     link: https://crossd.tech
  #     name: crossd.tech
copyright: Copyright &copy; 2024 St. Pölten University of Applied Sciences
repo_url: https://github.com/fh-crossd
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - include-markdown
  - privacy
  - search
  - glightbox
nav:
  - index.md
  - Installation:
    - installation/guide.md
    - installation/requirements.md
    - installation/secrets.md
    - installation/frontend_origin.md
    - installation/setup.md
    - installation/ingress.md
    - installation/adding_tasks.md
    - installation/backup_database.md
  - Components:
    - components/components.md
    - components/arangodb.md
    - components/redis.md
    - components/flower.md
    - components/crawlers.md
    - components/frontend.md
    - API: components/api/api.md
    - components/add_task.md
    - components/arango_init.md
    - components/external_services.md
    - components/ingress.md
  - "Known Issues": known_issues/known_issues.md
  - acknowledgements/acknowledgements.md
  - "|": "#"
  - "Health Monitor&nbsp;<svg style=\"padding-top:4px;padding-bottom:4px;\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d=\"M352 0c-12.9 0-24.6 7.8-29.6 19.8s-2.2 25.7 6.9 34.9L370.7 96 201.4 265.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L416 141.3l41.4 41.4c9.2 9.2 22.9 11.9 34.9 6.9s19.8-16.6 19.8-29.6V32c0-17.7-14.3-32-32-32H352zM80 32C35.8 32 0 67.8 0 112V432c0 44.2 35.8 80 80 80H400c44.2 0 80-35.8 80-80V320c0-17.7-14.3-32-32-32s-32 14.3-32 32V432c0 8.8-7.2 16-16 16H80c-8.8 0-16-7.2-16-16V112c0-8.8 7.2-16 16-16H192c17.7 0 32-14.3 32-32s-14.3-32-32-32H80z\"/></svg>": "https://health.crossd.tech"
  - "Project Blog&nbsp;<svg style=\"padding-top:4px;padding-bottom:4px;\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d=\"M352 0c-12.9 0-24.6 7.8-29.6 19.8s-2.2 25.7 6.9 34.9L370.7 96 201.4 265.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L416 141.3l41.4 41.4c9.2 9.2 22.9 11.9 34.9 6.9s19.8-16.6 19.8-29.6V32c0-17.7-14.3-32-32-32H352zM80 32C35.8 32 0 67.8 0 112V432c0 44.2 35.8 80 80 80H400c44.2 0 80-35.8 80-80V320c0-17.7-14.3-32-32-32s-32 14.3-32 32V432c0 8.8-7.2 16-16 16H80c-8.8 0-16-7.2-16-16V112c0-8.8 7.2-16 16-16H192c17.7 0 32-14.3 32-32s-14.3-32-32-32H80z\"/></svg>": "https://crossd.tech"
  - "|": "#"
  - "Legal Information": legal.md
