site_name: CrOSSD Documentation
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
use_directory_urls: false
extra:
  generator: false
copyright: Copyright &copy; 2024 St. Pölten University of Applied Sciences
repo_url: https://github.com/fh-crossd
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
plugins:
  - include-markdown
  - privacy
  - search
nav:
  - index.md
  - Installation:
    - installation/guide.md
    - installation/requirements.md
    - installation/secrets.md
    - installation/frontend_origin.md
    - installation/setup.md
    - installation/ingress.md
    - installation/adding_tasks.md
    - installation/backup_database.md
  - Components:
    - components/components.md
    - components/arangodb.md
    - components/redis.md
    - components/flower.md
    - components/crawlers.md
    - components/frontend.md
    - API: components/api/api.md
    - components/add_task.md
    - components/arango_init.md
    - components/external_services.md
    - components/ingress.md
  - known_issues/known_issues.md
  - acknowledgements/acknowledgements.md
